# Generated by Django 4.2.3 on 2023-11-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_customuser_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="prevalence_counting_user",
            field=models.BooleanField(default=False),
        ),
    ]
