# Generated by Django 4.2.3 on 2023-11-28 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_customuser_prevalence_counting_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="prevalence_counting_user",
            new_name="is_prevalence_counting_user",
        ),
    ]
