# Generated by Django 4.2.3 on 2023-08-01 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "repository",
            "0007_alter_dataset_options_alter_organization_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="abbr_zip_code_at_birth_token",
            field=models.CharField(
                blank=True,
                help_text="Abbreviated zip code",
                max_length=1024,
                validators=[django.core.validators.MinLengthValidator(1024)],
                verbose_name="Abbreviated zip code at birth",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="zip_code_at_birth_token",
            field=models.CharField(
                blank=True,
                help_text="Zip code",
                max_length=1024,
                validators=[django.core.validators.MinLengthValidator(1024)],
                verbose_name="Zip code at birth",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="address_at_bith_token",
            field=models.CharField(
                blank=True,
                help_text="Street address",
                max_length=1024,
                validators=[django.core.validators.MinLengthValidator(1024)],
                verbose_name="Address at birth",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="city_at_birth_token",
            field=models.CharField(
                blank=True,
                help_text="City name",
                max_length=1024,
                validators=[django.core.validators.MinLengthValidator(1024)],
                verbose_name="City at birth",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="country_at_birth_token",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-1 alpha-3",
                max_length=1024,
                validators=[django.core.validators.MinLengthValidator(1024)],
                verbose_name="Country at birth",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="date_of_birth_token",
            field=models.CharField(
                help_text="YYYY-MM-DD",
                max_length=1024,
                validators=[django.core.validators.MinLengthValidator(1024)],
                verbose_name="Date of birth",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="first_name_soundex_token",
            field=models.CharField(
                blank=True,
                max_length=1024,
                validators=[django.core.validators.MinLengthValidator(1024)],
                verbose_name="First name soundex",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="first_name_token",
            field=models.CharField(
                max_length=1024,
                validators=[django.core.validators.MinLengthValidator(1024)],
                verbose_name="First name",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="full_name_token",
            field=models.CharField(
                blank=True,
                max_length=1024,
                validators=[django.core.validators.MinLengthValidator(1024)],
                verbose_name="Full name",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="gender_token",
            field=models.CharField(
                blank=True,
                help_text="M or F",
                max_length=1024,
                validators=[django.core.validators.MinLengthValidator(1024)],
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="last_name_soundex_token",
            field=models.CharField(
                blank=True,
                max_length=1024,
                validators=[django.core.validators.MinLengthValidator(1024)],
                verbose_name="Last name soundex",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="last_name_token",
            field=models.CharField(
                max_length=1024,
                validators=[django.core.validators.MinLengthValidator(1024)],
                verbose_name="Last name",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="middle_name_token",
            field=models.CharField(
                blank=True,
                max_length=1024,
                validators=[django.core.validators.MinLengthValidator(1024)],
                verbose_name="Middle name",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="state_at_birth_token",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-2",
                max_length=1024,
                validators=[django.core.validators.MinLengthValidator(1024)],
                verbose_name="State at birth",
            ),
        ),
    ]
