# Generated by Django 4.2.3 on 2023-11-02 20:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0011_alter_dataset_organization_alter_dataset_tags_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
