# Generated by Django 4.2.3 on 2023-12-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "prevalence",
            "0003_alter_diseasestats_options_alter_globalstats_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="do_id",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
