# Generated by Django 4.2.3 on 2023-12-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prevalence", "0004_disease_do_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disease",
            name="icd10_id",
        ),
        migrations.RemoveField(
            model_name="disease",
            name="omim_id",
        ),
        migrations.RemoveField(
            model_name="disease",
            name="orpha_id",
        ),
        migrations.RemoveField(
            model_name="disease",
            name="snomed_id",
        ),
        migrations.RemoveField(
            model_name="disease",
            name="synonyms",
        ),
        migrations.AddField(
            model_name="disease",
            name="EFO",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="GARD",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="ICD10CM",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="ICD11",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="ICD9CM",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="ICDO",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="KEGG",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="MEDDRA",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="MESH",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="NCI",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="OMIM",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="ORDO",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="SNOMEDCT_US_2020_03_01",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="SNOMEDCT_US_2021_07_31",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="SNOMEDCT_US_2021_09_01",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="SNOMEDCT_US_2022_07_31",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="SNOMEDCT_US_2023_03_01",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="SNOMEDCT_US_2023_09_01",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="SNOMEDCT_US_2023_10_01",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="disease",
            name="UMLS_CUI",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
