# Generated by Django 4.2.3 on 2023-12-29 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("datasets", "0013_remove_submission_abbr_zip_code_at_birth_token"),
        ("prevalence", "0006_disease_do_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientsbysource",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="datasets.source"
            ),
        ),
    ]
