# Generated by Django 4.2.3 on 2024-01-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prevalence", "0008_diseasestats_global_stats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disease",
            name="do_id",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
